[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]] #   CHAK
[patches.pattern]
target = 'card.lua'
pattern = '''if (self.ability.set == 'Voucher' or self.config.center.demo) and (self.ability.name ~= 'Antimatter' or not (self.config.center.discovered or self.bypass_discovery_center)) then'''
position = "before"
match_indent = true
payload = '''
--  CHAK START
if self.ability.set == 'ChakraConsumableType' then
    self.children.center:draw_shader('negative_shine', nil, self.ARGS.send_to_shader)
end
if self.ability.set == 'ChakraBoosterType' then
    self.children.center:draw_shader('booster', nil, self.ARGS.send_to_shader)
end
-- CHAK END
'''

[[patches]] #   CHAK
[patches.pattern]
target = 'card.lua'
pattern = '''if self.ability.name == 'Invisible Joker' and (self.config.center.discovered or self.bypass_discovery_center) then'''
position = "before"
match_indent = true
payload = '''
--  CHAK START
if self.config.center.key == 'j_chak_unending_torment' and (self.config.center.discovered or self.bypass_discovery_center) then
    self.children.center:draw_shader('booster', nil, self.ARGS.send_to_shader)
end

if self.config.center.key == 'j_chak_etheric_joker' and (self.config.center.discovered or self.bypass_discovery_center) then
    self.children.center:draw_shader('negative_shine', nil, self.ARGS.send_to_shader)
end
-- CHAK END
'''

[[patches]] #   CHAK
[patches.pattern]
target = 'globals.lua'
pattern = '''DARK_EDITION = {0,0,0,1},'''
position = "before"
match_indent = true
payload = '''
--  CHAK START
CHAKRA_EDITION = {0,1,1,1},
--  CHAK END
'''

[[patches]] #   CHAK
[patches.pattern]
target = 'game.lua'
pattern = '''col_op = {'RED','BLUE','GREEN','BLACK','L_BLACK','WHITE','EDITION','DARK_EDITION','ORANGE','PURPLE'},'''
position = "at"
match_indent = true
payload = '''col_op = {'RED','BLUE','GREEN','BLACK','L_BLACK','WHITE','EDITION','DARK_EDITION','CHAKRA_EDITION','ORANGE','PURPLE'},'''

[[patches]] #   CHAK
[patches.pattern]
target = 'misc_functions.lua'
pattern = '''dark_edition = G.C.DARK_EDITION,'''
position = "before"
match_indent = true
payload = '''chakra_edition = G.C.CHAKRA_EDITION,'''

[[patches]] #   CHAK
[patches.pattern]
target = 'game.lua'
pattern = '''self.C.DARK_EDITION[1] = 0.6+0.2*math.sin(self.TIMERS.REAL*1.3)'''
position = "before"
match_indent = true
payload = '''
--  CHAK START
self.C.CHAKRA_EDITION[1] = 0.1+0.2*(1- math.sin(self.TIMERS.REAL*1.25))
self.C.CHAKRA_EDITION[3] = 0.2+0.2*(1- math.sin(self.TIMERS.REAL*1.2))
self.C.CHAKRA_EDITION[2] = 0.65+0.2*math.sin(self.TIMERS.REAL*1.35)
--  CHAK END
'''